# Generated by Django 5.1.4 on 2026-05-17 07:57

import apps.presence.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, help_text="Free text: 'M51 with 600s exposures'", max_length=200)),
                ('anonymous', models.BooleanField(default=False, help_text="Show as 'someone' on the map")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.presence.models._default_expires_at)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presence_checkin',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['place', 'expires_at'], name='presence_ch_place_i_7bff9b_idx'), models.Index(fields=['user', 'expires_at'], name='presence_ch_user_id_f7e400_idx')],
            },
        ),
    ]
