# Generated by Django 5.1.4 on 2026-05-18 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_opening_hours_schedule'),
        ('presence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto_schedule', 'Auto (opening hours)')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for system-generated check-ins (source=auto_schedule).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['source', 'expires_at'], name='presence_ch_source_4df84b_idx'),
        ),
    ]
