# Generated by Django 5.1.4 on 2026-05-17 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('language', models.CharField(default='cs', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_project',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('contributor', 'Contributor'), ('observer', 'Observer')], default='contributor', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
            ],
            options={
                'db_table': 'projects_membership',
                'ordering': ['created_at'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GHRepo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_login', models.CharField(max_length=80)),
                ('repo_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=40)),
                ('open_issues', models.IntegerField(default=0)),
                ('default_branch', models.CharField(blank=True, max_length=80)),
                ('last_commit_at', models.DateTimeField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True, max_length=300)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gh_repos', to='projects.project')),
            ],
            options={
                'db_table': 'projects_ghrepo',
                'ordering': ['owner_login', 'repo_name'],
                'unique_together': {('project', 'owner_login', 'repo_name')},
            },
        ),
    ]
