# Generated by Django 5.1.4 on 2026-05-17 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable label', max_length=120)),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('prefix', models.CharField(help_text='First 8 chars of plaintext for UI', max_length=12)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publishing_api_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='publishing__user_id_362e77_idx')],
            },
        ),
    ]
