# Generated by Django 5.1.4 on 2026-05-17 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('place_followed_checkin', 'Check-in on followed place'), ('place_any_checkin', 'Any check-in'), ('article_published', 'Article published'), ('event_status_changed', 'Event status changed'), ('project_lifecycle', 'Project created/deleted'), ('campaign_status_changed', 'Campaign status changed')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_discord_preference',
                'ordering': ['kind'],
                'unique_together': {('user', 'kind')},
            },
        ),
    ]
