# Generated by Django 5.1.4 on 2026-05-18 19:05

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_meeting_url'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='events_comm_event_i_09c51b_idx',
            old_name='events_comm_event_i_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='events_comm_parent__f0149b_idx',
            old_name='events_comm_parent__idx',
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
