# Generated by Django 5.1.4 on 2026-05-19 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='discussion_allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_event_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='discussion_visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('members', 'Members'), ('allowlist', 'Selected members'), ('private', 'Private')], default='', help_text='Empty = inherit from `visibility`', max_length=12),
        ),
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Members'), ('allowlist', 'Selected members'), ('private', 'Private')], default='public', max_length=12),
        ),
    ]
