# Generated by Django 5.1.4 on 2026-05-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_allowed_users_event_discussion_allowed_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discord_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='geocache_url',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='event',
            name='radio_frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
