# Generated by Django 5.1.4 on 2026-05-17 14:22

import apps.uploads.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=300, upload_to=apps.uploads.models._upload_path)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('other', 'Other')], default='image', max_length=10)),
                ('mime', models.CharField(blank=True, max_length=80)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploads_upload',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='uploads_upl_user_id_a1664e_idx')],
            },
        ),
    ]
