# Generated by Django 5.1.4 on 2026-05-17 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('observatory_public', 'Public observatory'), ('observatory_private', 'Private observatory'), ('spot_permanent', 'Permanent observation spot'), ('spot_temporary', 'Temporary observation spot')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('lat', models.FloatField(help_text='Latitude (WGS84, -90..90)')),
                ('lon', models.FloatField(help_text='Longitude (WGS84, -180..180)')),
                ('elevation_m', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('website', models.URLField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=160)),
                ('opening_hours', models.CharField(blank=True, max_length=160)),
                ('bortle_class', models.FloatField(blank=True, help_text='Light pollution Bortle scale 1..9', null=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='For temporary places', null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='For temporary places', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'places_place',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['kind'], name='places_plac_kind_91076b_idx'), models.Index(fields=['status'], name='places_plac_status_8eccee_idx'), models.Index(fields=['lat', 'lon'], name='places_plac_lat_d1ae26_idx'), models.Index(fields=['valid_to'], name='places_plac_valid_t_7b1c3f_idx')],
            },
        ),
    ]
