# Generated by Django 5.1.4 on 2026-05-18 06:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BortleMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(help_text='Bortle class 1..9')),
                ('source', models.CharField(choices=[('manual', 'Manual reading'), ('viirs_black_marble', 'Auto: VIIRS Black Marble'), ('viirs_dnb_latest', 'Auto: VIIRS DNB latest')], max_length=24)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('luminance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bortle_measurements', to='places.place')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bortle_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'places_bortle_measurement',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['place', '-measured_at'], name='places_bort_place_i_3d9312_idx'), models.Index(fields=['source'], name='places_bort_source_be4d34_idx')],
            },
        ),
    ]
