# Generated by Django 5.1.4 on 2026-05-18 07:41

from django.db import migrations, models


def backfill_dual(apps, schema_editor):
    """Populate the new dual fields from existing data:
    - bortle_class_manual ← latest BortleMeasurement(source=manual).value, or bortle_class if no measurements
    - bortle_class_map ← latest BortleMeasurement(source in viirs_*).value
    """
    Place = apps.get_model("places", "Place")
    BM = apps.get_model("places", "BortleMeasurement")
    for p in Place.objects.all():
        manual_m = (
            BM.objects.filter(place_id=p.pk, source="manual")
            .order_by("-measured_at")
            .first()
        )
        auto_m = (
            BM.objects.filter(place_id=p.pk, source__startswith="viirs_")
            .order_by("-measured_at")
            .first()
        )
        if manual_m:
            p.bortle_class_manual = manual_m.value
        elif p.bortle_class is not None:
            # Seeded value with no history rows — treat as manual
            p.bortle_class_manual = p.bortle_class
        if auto_m:
            p.bortle_class_map = auto_m.value
            p.bortle_class_map_source = auto_m.source
            p.bortle_class_map_updated_at = auto_m.measured_at
        p.save(
            update_fields=[
                "bortle_class_manual",
                "bortle_class_map",
                "bortle_class_map_source",
                "bortle_class_map_updated_at",
            ]
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_bortlemeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='bortle_class_manual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='bortle_class_map',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='bortle_class_map_source',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='place',
            name='bortle_class_map_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='bortle_class',
            field=models.FloatField(blank=True, help_text='Deprecated; use bortle_class_manual / bortle_class_map', null=True),
        ),
        migrations.RunPython(backfill_dual, reverse_code=noop_reverse),
    ]
