# Generated by Django 5.1.4 on 2026-05-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_dual_bortle'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='opening_hours_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
