# Generated by Django 5.1.4 on 2026-05-17 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('google', 'Google'), ('mastodon', 'Mastodon')], max_length=16)),
                ('provider_user_id', models.CharField(max_length=120)),
                ('provider_username', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('avatar_url', models.URLField(blank=True)),
                ('access_token', models.CharField(blank=True, max_length=400)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_identity',
                'indexes': [models.Index(fields=['user', 'provider'], name='accounts_id_user_id_ddf04b_idx'), models.Index(fields=['email'], name='accounts_id_email_c53561_idx')],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
