# Generated by Django 5.1.4 on 2026-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zenodo_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='zenodo_use_sandbox',
            field=models.BooleanField(default=True, help_text='Use sandbox.zenodo.org instead of zenodo.org'),
        ),
    ]
