# Generated by Django 5.1.4 on 2026-05-17 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_zenodo_token_profile_zenodo_use_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_url', models.URLField(help_text='e.g. https://mastodon.social', unique=True)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('vapid_key', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, help_text='Display name from the instance', max_length=160)),
                ('redirect_uri', models.URLField(help_text='The redirect we registered with', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_mastodon_instance',
                'ordering': ['base_url'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='identity',
            name='provider_instance',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together={('provider', 'provider_user_id', 'provider_instance')},
        ),
    ]
