# Generated by Django 5.1.4 on 2026-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mastodoninstance_alter_identity_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mastodon_autopost_checkin',
            field=models.BooleanField(default=False),
        ),
    ]
