# Generated by Django 5.1.4 on 2026-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_last_login_city_user_last_login_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='map_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
