# Generated by Django 5.1.4 on 2026-05-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_map_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_utc',
            field=models.BooleanField(default=True),
        ),
    ]
