# Generated by Django 5.1.4 on 2026-05-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_show_local_profile_show_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='discord_guild_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='identity',
            name='discord_guild_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='identity',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('google', 'Google'), ('mastodon', 'Mastodon'), ('discord', 'Discord'), ('gitlab', 'GitLab'), ('facebook', 'Facebook')], max_length=16),
        ),
    ]
