# Generated by Django 5.1.4 on 2026-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_identity_discord_guild_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='identity',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='zooniverse_in_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identity',
            name='zooniverse_membership_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('google', 'Google'), ('mastodon', 'Mastodon'), ('discord', 'Discord'), ('gitlab', 'GitLab'), ('facebook', 'Facebook'), ('zooniverse', 'Zooniverse')], max_length=16),
        ),
    ]
