# Generated by Django 5.1.4 on 2026-05-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_identity_refresh_token_identity_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='access_token',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='identity',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
