# Generated by Django 5.1.4 on 2026-05-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfra',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('pmtiles_path', models.CharField(default='/var/lib/astrozor/pmtiles/europe.pmtiles', max_length=300)),
                ('pmtiles_source_url', models.URLField(default='https://build.protomaps.com/20260301.pmtiles', help_text='Protomaps Daily build URL — update to the latest date when refreshing', max_length=500)),
                ('pmtiles_size_bytes', models.BigIntegerField(default=0)),
                ('pmtiles_last_update', models.DateTimeField(blank=True, null=True)),
                ('pmtiles_job_id', models.CharField(blank=True, max_length=80)),
                ('pmtiles_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('error', 'Error')], default='idle', max_length=10)),
                ('pmtiles_status_message', models.TextField(blank=True)),
                ('photon_url', models.URLField(default='http://photon:2322', max_length=300)),
                ('photon_last_import', models.DateTimeField(blank=True, null=True)),
                ('photon_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('error', 'Error')], default='idle', max_length=10)),
                ('photon_status_message', models.TextField(blank=True)),
                ('photon_imported_size_mb', models.BigIntegerField(default=0)),
                ('tile_backend', models.CharField(choices=[('osm', 'OSM'), ('pmtiles', 'PMTiles (self-hosted)')], default='osm', max_length=10)),
                ('search_backend', models.CharField(choices=[('nominatim', 'Nominatim (proxied)'), ('photon', 'Photon (self-hosted)')], default='nominatim', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_map_infra',
            },
        ),
    ]
