# Generated by Django 5.1.4 on 2026-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapinfra',
            name='pmtiles_source_url',
            field=models.URLField(blank=True, default='', help_text='Protomaps Daily build URL. Leave blank to auto-pick the latest from https://build-metadata.protomaps.dev/builds.json', max_length=500),
        ),
    ]
