# Generated by Django 5.1.4 on 2026-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_light_pollution_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_black_marble_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_black_marble_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_black_marble_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('error', 'Error')], default='idle', max_length=10),
        ),
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_black_marble_status_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_black_marble_tile_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_viirs_dnb_cached_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_viirs_dnb_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_viirs_dnb_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_viirs_dnb_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('error', 'Error')], default='idle', max_length=10),
        ),
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_viirs_dnb_status_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mapinfra',
            name='light_pollution_viirs_dnb_tile_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
