# Generated by Django 5.1.4 on 2026-05-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_mapinfra_light_pollution_black_marble_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapinfra',
            name='chat_text_max_length',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
