# Generated by Django 5.1.4 on 2026-05-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_clouds_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapinfra',
            name='light_pollution_black_marble_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error')], default='idle', max_length=10),
        ),
        migrations.AlterField(
            model_name='mapinfra',
            name='light_pollution_viirs_dnb_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error')], default='idle', max_length=10),
        ),
        migrations.AlterField(
            model_name='mapinfra',
            name='photon_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error')], default='idle', max_length=10),
        ),
        migrations.AlterField(
            model_name='mapinfra',
            name='pmtiles_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error')], default='idle', max_length=10),
        ),
    ]
