# Generated by Django 5.1.4 on 2026-05-17 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=400)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('target_kind', models.CharField(choices=[('place', 'Place')], default='place', max_length=16)),
                ('target_id', models.CharField(help_text='Slug of target', max_length=64)),
                ('poll_interval_seconds', models.IntegerField(default=1800)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=40)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feeds_feedsource',
                'ordering': ['-created_at'],
                'unique_together': {('url', 'target_kind', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guid', models.CharField(db_index=True, max_length=400)),
                ('title', models.CharField(max_length=400)),
                ('link', models.URLField(max_length=600)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feeds.feedsource')),
            ],
            options={
                'db_table': 'feeds_feeditem',
                'ordering': ['-published_at', '-fetched_at'],
                'indexes': [models.Index(fields=['source', '-fetched_at'], name='feeds_feedi_source__8199cf_idx')],
                'unique_together': {('source', 'guid')},
            },
        ),
    ]
