# Generated by Django 5.1.4 on 2026-05-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='kind',
            field=models.CharField(choices=[('rss', 'RSS / Atom'), ('mastodon_hashtag', 'Mastodon hashtag')], default='rss', max_length=24),
        ),
    ]
