# Generated by Django 5.1.4 on 2026-05-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_thread_and_attachments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_parent__ede592_idx',
            old_name='chat_messag_parent__idx',
        ),
    ]
