# Generated by Django 5.1.4 on 2026-05-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=12),
        ),
    ]
