# Generated by Django 5.1.4 on 2026-05-19 05:01

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_campaign_tags'),
        ('core', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
