# Generated by Django 5.1.4 on 2026-05-19 18:18

import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_alter_campaign_tags'),
        ('core', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZooniverseGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zooniverse_group_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(default='Astrozor', max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('join_token', models.CharField(blank=True, max_length=120)),
                ('stats_visibility', models.CharField(blank=True, max_length=40)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'citizen_zooniverse_group',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='zooniverse_workflow_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ZooniverseProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zooniverse_id', models.PositiveIntegerField(unique=True)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('owner_login', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('introduction', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('background_url', models.URLField(blank=True)),
                ('primary_language', models.CharField(blank=True, max_length=8)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('classifications_count', models.BigIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('astrozor_curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_zooniverse_projects', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'citizen_zooniverse_project',
                'ordering': ['-is_featured', '-classifications_count'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='zooniverse_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='citizen.zooniverseproject'),
        ),
        migrations.CreateModel(
            name='ZooniverseStatsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('project', 'Project'), ('group', 'Group'), ('user', 'User')], max_length=10)),
                ('subject_id', models.BigIntegerField()),
                ('period', models.CharField(choices=[('total', 'Total'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=8)),
                ('date', models.DateField()),
                ('count', models.BigIntegerField(default=0)),
                ('time_spent_s', models.PositiveIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'citizen_zooniverse_stats_snapshot',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id', 'period', 'date'], name='citizen_zoo_subject_b83a1a_idx')],
                'unique_together': {('subject_type', 'subject_id', 'period', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='zooniverseproject',
            index=models.Index(fields=['is_featured', '-classifications_count'], name='citizen_zoo_is_feat_73c587_idx'),
        ),
    ]
