# Generated by Django 5.1.4 on 2026-05-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0008_sprintparticipant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sprintparticipant',
            new_name='citizen_spr_sprint__e6f54c_idx',
            old_name='citizen_spr_sprint__d4d3f1_idx',
        ),
    ]
